version: '3.8'

services:
  web:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    command:   gunicorn doguide.wsgi:application --bind 0.0.0.0:7000
    image: iridescentoctopus/ci-cd-project:latest
    ports:
      - "7000:7000"
    env_file:
       - ./.env
    networks:
      - django-ci-example
  
  
networks:
  django-ci-example:
    
